language: python
dist: xenial
sudo: true

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d

scripts:
  pipenv run flake8 .